### ISSUE TITLE
[Feature request] Render inline images in comments 

### ISSUE THREAD

**Issue by AlbertCerfeda** [aaron-bond/better-comments#325]
Hi,
would it be possible to add a feature where an image would be rendered in a comment after specifying a path (e.g with a markdown comment) ?

edit: This would be similar to what [this](https://marketplace.visualstudio.com/items?itemName=MsBishop.ImageComments) extension does, but is available only on Visual Studio

**Comment by altimmons** [comment]
This isnt really realistic due to the implementation of the editor in VSCode.
What you are looking at is not a browser screen where you can just stick mages in - its a general text editor.  It can change colors and fonts.  And thats about  it.

Even in markdown and asciidoc, adding an image doesnt work, it has to be rendered to HTML then shown in an HTML pane. 

Glyphs and Character Icons (see Nerdfont) may be possible.  But would require using that font.

You cant even change font withn a document.  The entire document (and all docs) is a single font to render.

I believe the underlying framework is Monaco so you can look it up and take a look at the implementation

**Comment by altimmons** [comment]
I use VSCode ASCII DOC and Markdown a lot for all of my notes - all of them, hundreds and hundreds of pages at this point.  I really wish this and other similar things were possible, and I have done extensive research to try and push the limits of possibility as much as possible

**Comment by aaron-bond** [comment]
Yeah as @altimmons says, glyphs are the closest you can get with the text editor AFAIK.
