### ISSUE TITLE
Randomly stops working

### ISSUE THREAD

**Issue by gmiwoj** [aaron-bond/better-comments#35]
Sometimes it works, then it stops working for no reason and it stays like this, only way i to get it back is to keep reloading, disabling and enabling shit, until it eventually pops back again when it feels like it. 

this is my code from  user settings
```
    "better-comments.multilineComments": true, 
    "better-comments.tags": [
        {
            "tag": "!",
            "color": "#FF2D00",
            "strikethrough": false
        },
        {
            "tag": "?",
            "color": "#3498DB",
            "strikethrough": false
        },
        {
            "tag": "//",
            "color": "#474747",
            "strikethrough": true
        },
        {
            "tag": "todo",
            "color": "#FF8C00",
            "strikethrough": false
        },
        {
            "tag": "*",
            "color": "#98C379",
            "strikethrough": false
        }
    ],
```

**Comment by aaron-bond** [comment]
Hmm, someone raised a similar issue before but I couldn't repro.

Can you tell me:
Is it a multi folder workspace?
What languages are you working with?

**Comment by BennyHarv3** [comment]
I'm also experiencing this issue with Groovy files, both with and without a workspace. Same configuration, and both with and without folders (e.g., just a top-level folder named `test.groovy` doesn't work).

**Comment by nickprivalov** [comment]
I think I had something similar happen to me just now.  I'm working on Pebble SDK C files, with lots of Better Comments tags being used, and at some points it seemed like the editor was failing to properly discern what lines were supposed to be changed in color or not.  It would seem to make certain sections of the code (by line) render in the incorrect color.

I had some other files open in the same window but reside in a folder in the workspace root.  Moving them to the same folder, the workspace root, solved the issues.

**Comment by aaron-bond** [comment]
Hey thanks for the info. Were the files quite large?

To confirm: having files open in the editor from outside your workspace root and moving to ones inside seemed to cause issues?

**Comment by nickprivalov** [comment]
The one that was in the workspace root ('main.c') is fairly large sized, I think maybe ~150 lines, while the one that was in the folder ('main_old.c') is over 400 lines.  I'm rewriting a Pebble watch app manually to make the code cleaner, less redundant, etc., and I have both files open at the same time in two panes, in the same VSC window.

The issue occurred when 'main.c' was in the workspace root folder, and 'main_old.c' was in a folder named 'old' in the workspace root.  Moving the files in the 'old' folder to the workspace root solved the problem.

Very interesting behavior, but figured I'd share it because it seems to be a rare case.

**Comment by aaron-bond** [comment]
Thanks for the suggestions here @nickprivalov - mentioning the two open files at once was enough to get me onto the right track to chase down the bug. That one's been giving me the run around for a while now, so thanks :)
