### ISSUE TITLE
Space being highlighted with comments

### ISSUE THREAD

**Issue by 4z0t** [aaron-bond/better-comments#452]
If there is enabled display of space symbols extension highlights them as well:
![image](https://user-images.githubusercontent.com/84857900/204558396-4c5e9f9a-936c-42ea-ad9d-991767655c0b.png)

**Comment by aarondill** [comment]
This seems like desired behavior. Is there a particular reason this is unfavorable to you?

**Comment by 4z0t** [comment]
It makes comments unreadable.

**Comment by aarondill** [comment]
Based on the way regular expressions parse matches, and the way the code is styled(through a VSCode range), I don't think this is even possible to change even if the devs decided this was a change or option they wanted to add. 
If it's more important to you to not have it highlighted than to show *every* whitespace, you can set whitespace rendering to "boundary", otherwise, perhaps use another character(ie underscore) for comment word breaks

**Comment by 4z0t** [comment]
But regular comments aren't changed, it feels off due to highlighted ones.

**Comment by lrslei** [comment]
I have the same issue. I thought there would have been a way for better-comments to avoid colouring the specific character vscode uses to highlight whitespace, as this issue doesn't happen in regular comments or other vscode syntax highlighting

**Comment by marcellino-ornelas** [comment]
Running into the same issue.

Having whitespace get colorized makes the comments very unreadable.

**Comment by aarondill** [comment]
[this patch](https://github.com/microsoft/vscode/pull/168732) seems like it should fix this soon
this is a VSCode limitation, not one with the extension

**Comment by aarondill** [comment]
this is a VSCode limitation, not one with the extension

**Comment by aaron-bond** [comment]
I don't tend to make too many updates to this extension these days due to other commitments, but this one is a personal pet peeve that's never been possible. I'll gladly make the update when this comes in!
