### ISSUE TITLE
enhancement: starting point of striked text

### ISSUE THREAD

**Issue by pakLebah** [aaron-bond/better-comments#46]
Just updated to the latest version of this extension, v.1.2.0. And I got some enhancement ideas.

The new striked text feature is very useful. However, there's a little glitch that makes it look imperfect when it's used within the jsdoc section. It's the starting point of the striked text. Instead of starting from the beginning of line, could you make it to start from the asterisk? Like it's shown at the line number 33 that starts from the `//`.

Screenshot attached, the glitch is shown at the line number 16 (I changed `//` to `-`).

Screenshot:
![better-comments-report](https://user-images.githubusercontent.com/11470932/37629804-74306176-2c13-11e8-86cd-25a03f5a3eed.png)

**Comment by aaron-bond** [comment]
Ah good catch. This is because the regex is starting at the beginning of the line. I'll take a look :)

**Comment by pakLebah** [comment]
Just another small suggestion. I propose the extension to provide these default (and common) comment marks:

`* #00AA00` : for information or modification.
`? #BABA00` :  for query or confirmation.
`! #DD2222` : for alert or warning.
`+ #3355FF` : for addition or new feature.
`- #666666` : for removal or obsolete feature (instead of `//`).
`# #BBBBBB` : for heading or title.
`TODO #FF8C00` : for to-do list.

Screenshot:
![jepretan layar 2018-03-20 pada 21 17 03](https://user-images.githubusercontent.com/11470932/37660178-5eb03508-2c84-11e8-8dd9-eb9a589e2dff.png)

**Comment by aaron-bond** [comment]
Ooh I like the white. That's a neat idea. I'm not sure about updating the defaults since I don't want to knock out anyone's custom configurations... I think I'll use the white one personally though.

I'll need to investigate a bit to see what happens to custom settings when the extension updates.

For this bug though, here's the updated decorations with the proper regex:
![image](https://user-images.githubusercontent.com/14099631/37662616-5835eaea-2c4f-11e8-8cc3-bceb276a2ab7.png)

**Comment by pakLebah** [comment]
That's better. Can't wait to get the update. 😊
