### ISSUE TITLE
Feature request: more font style options for comment tag

### ISSUE THREAD

**Issue by pakLebah** [aaron-bond/better-comments#50]
Currently, this extension only supports color and strikethrough options. Could you please add more font style options for comment tag? 

Here's some other font style options that can be provided:
- **bold**
- _italic_
- <u>underline</u>
- font size
- font family

Thank you.

**Comment by aaron-bond** [comment]
Bold and Italic are probably pretty trivial to add (apart from changing default configs). I'll take a look

**Comment by pakLebah** [comment]
Perhaps you should just put css `font-style` attribute into settings. That will enable all kind of font formatting, I suppose.

**Comment by jackcoach** [comment]
I'd like to upvote this request. It would be a simple but great addition to the extension.

**Comment by miguel-pinto-prodmad** [comment]
> I'd like to upvote this request. It would be a simple but great addition to the extension.

+1

**Comment by ajgenius** [comment]
I spent way too much time working out how to build the extension, but then ended making a really small patch for what was available and obvious for my own purposes.

This patch won't work by default because these options require a newer vscode dependency than what is in the package files which are referencing the much older "vscode", instead of the active "@types/vscode". I verified the newer versions have supported fontStyle and fontWeight for over a year, and if you can fix the package.json and package-lock.json accordingly it works fine.

Adds textDecoration instead of just underline, but I still left strikethrough as a fallback option because of default/existing configs. It also adds fontStyle for explicit italic/normal, fontWeight for "bold" (or "600" for semibold, or maybe 200 for light etc), & border. Not actually sure there is any value in having border exposed, but it works so I added it. Also it might make more sense to just do an italic boolean, false for normal, true for italic,  unset for current theme. (Unless someone needs oblique instead?)

Font size and family aren't exposed by vscode that I saw. 

[addmoreoptions.txt](https://github.com/aaron-bond/better-comments/files/3536242/addmoreoptions.txt)

**Comment by HosseinAgha** [comment]
@aaron-bond adding font-style would be awesome!

**Comment by Fr33maan** [comment]
@aaron-bond I've partially implemented the feature, made a PR with feature + doc

**Comment by aaron-bond** [comment]
Thanks to @Fr33maan this feature will be in the next version of the extension, so keep an eye out :)
