### ISSUE TITLE
Better Comments Extension isn't working with multiline comments in C, C++, Java etc. 

### ISSUE THREAD

**Issue by kaustubh-tripathi-1** [aaron-bond/better-comments#534]
![Editor](https://github.com/user-attachments/assets/c18a540a-39d3-4aea-9044-a71fe43d0b68)
![Settings JSON](https://github.com/user-attachments/assets/f7a5b5b1-9572-4acb-a31f-c90066ceaffc)

**Better Comments Extension doesn't work with multiline comments in C, C++, Java etc. even though I have set this setting to be true in settings.json file. 
It is working fine in HTML, CSS but with C, C++ etc. it is only working with single line comments, not multi lint comments.

**_Please look into this issue._**

PFA screenshots of the same.

Below are the extension settings -

"better-comments.multilineComments": true,
  "better-comments.highlightPlainText": true,
  "better-comments.tags": 
  [
    {
      "tag": "!",
      "color": "#FF2D00",
![Editor](https://github.com/user-attachments/assets/b1b0c043-6178-4d48-b85e-94d832302f00)
![Settings JSON](https://github.com/user-attachments/assets/b6417d8d-664c-4f9d-bfbf-813326c3fcdf)

      "strikethrough": false,
      "underline": false,
      "backgroundColor": "transparent",
      "bold": true,
      "italic": false
    },
    {
      "tag": "?",
      "color": "#3498DB",
      "strikethrough": false,
      "underline": false,
      "backgroundColor": "transparent",
      "bold": true,
      "italic": false
    },
    {
      "tag": "//",
      "color": "#474747",
      "strikethrough": true,
      "underline": false,
      "backgroundColor": "transparent",
      "bold": true,
      "italic": false
    },
    {
      "tag": "todo",
      "color": "#FF8C00",
      "strikethrough": false,
      "underline": false,
      "backgroundColor": "transparent",
      "bold": true,
      "italic": false
    },
    {
      "tag": "*",
      "color": "#98C379",
      "strikethrough": false,
      "underline": false,
      "backgroundColor": "transparent",
      "bold": true,
      "italic": false
    },
    {
      "tag": "&",
      "color": "#00fff2",
      "strikethrough": false,
      "underline": false,
      "backgroundColor": "transparent",
      "bold": true,
      "italic": false
    },
    {
      "tag": "$",
      "color": "#e5ff00",
      "strikethrough": false,
      "underline": false,
      "backgroundColor": "transparent",
      "bold": true,
      "italic": false
    },
    {
      "tag": "@",
      "color": "#33ff00",
      "strikethrough": false,
      "underline": false,
      "backgroundColor": "transparent",
      "bold": true,
      "italic": false
    },
    {
      "tag": "#",
      "color": "#df1256",
      "strikethrough": false,
      "underline": false,
      "backgroundColor": "transparent",
      "bold": true,
      "italic": false
    },
  ],

**Comment by DommDynamite** [comment]
I am seeing this, or something similar with TypeScript.

![image](https://github.com/user-attachments/assets/69135fff-57c4-4304-922f-d8ae33b925a0)

I don't know if this is part of what is causing this issue, but I have ESLint configured with the  rule:
    "multiline-comment-style": [
      "warn",
      "starred-block"
    ],
Which isn't allowing me to remove the * so that the ? is recognized.  I tried disabling the rule and now I can create multi-line comments but I just cannot include the * I have to instead make it whatever Better Comments symbol I need instead. This is not how it is demo'd as working in the extension page though. 

My work around: 
![image](https://github.com/user-attachments/assets/bd2772e9-f084-42a7-88df-645490089bf9)

From the extension page:
![image](https://github.com/user-attachments/assets/1f923511-1a03-4655-9ff3-23f9ca7c29d8)


I would like to know what is causing this. As I do have another machine at home with this extension and it works just fine as advertised out of the box. So maybe something is interfering with Better Comments?

**Comment by DommDynamite** [comment]
Just realized something. If I include two ** at the top of the comment is does work as advertised. 

![image](https://github.com/user-attachments/assets/bbb8a833-a3bc-44ec-8e73-6ea95ac3b31a)

**Comment by kaustubh-tripathi-1** [comment]
Yeah, now I get it too. Thanks @DommDynamite  for the revisit. 
**I'm closing this issue then as it's working fine.**
