### ISSUE TITLE
Disable VSCode TODO highlighting

### ISSUE THREAD

**Issue by mfour-merickson** [aaron-bond/better-comments#74]
Hey there, nice package!

I am curious, is there a setting where I can disable VSCode default TODO highlighting (unless this is from something else that I am not aware of). This is from a simple JS comment block.  I would much prefer your version :-)

![image](https://user-images.githubusercontent.com/31225533/41006279-b5f2269a-68d5-11e8-8519-b37d2c8bcc3b.png)

**Comment by mfour-merickson** [comment]
So, I found out which extension was doing the above (and have removed it), but now Better Comments is not highlighting in Orange as it does elsewhere

![image](https://user-images.githubusercontent.com/31225533/41006471-87dabd84-68d6-11e8-8d4b-5e72e1a3cb5b.png)

**Comment by aaron-bond** [comment]
Hi there :)
The reason here is that `/*` is not detected as a JSDoc comment. This means that the `*` at the start of your line is detected as your comment highlight symbol. To make yours work like you have it, change your opening tag to `/**`. That will trigger JSDoc syntax.

Alternatively, take the leading `*` off your TODO line :)

Check out the tests/samples folder for more examples of this in the typescript sample

**Comment by mfour-merickson** [comment]
@aaron-bond Excellent, thank you for the clarification.  All is working now as expected
