### ISSUE TITLE
Get Rid of Weird Space `.` Characters

### ISSUE THREAD

**Issue by ahmadawais** [aaron-bond/better-comments#83]
Love this plugin — is there a way to get rid of the spaces being displayed as a `.` character? 

Screenshot 👇
![image](https://on.ahmda.ws/suR7/c)

It's coz of `"editor.renderWhitespace": "all",` this setting and goes away on `none` and `boundary` options but I need `all` option set. It renders greyish in my theme for every place else.

![image](https://on.ahmda.ws/stRO/as)
Looking forward!

**Comment by aaron-bond** [comment]
Hi there!
This issue is the one that's hung around the longest within the code: #7 
As far as I can tell, there's no option within the decoration settings (or, there wasn't last time I looked) that would allow this as a config option. I'll take another look though.

P.S. what's the theme / font style you're using there? The comments look beaut!

**Comment by aaron-bond** [comment]
Just as a follow up, here's the VSCode repo issue that's pretty much why this is so hard:
https://github.com/Microsoft/vscode/issues/49462

**Comment by aaron-bond** [comment]
Please add any comments to the existing bug
